export default {
  "INIT":"INIT",
  "LOADING":"LOADING",
  "LOADED":"LOADED",
  "CONNECTING":"CONNECTING",
  "CONNECTED":"CONNECTED",
  "UPGRADING":"UPGRADING",
  "UPGRADED":"UPGRADED",
  "DOWNLOADING":"DOWNLOADING",
  "NETWORK_ERROR":"NETWORK_ERROR",
}